### ISSUE TITLE
Check how runtime files added in different projects

### ISSUE THREAD

**Issue by ProKn1fe** [ProKn1fe/WebView2.Runtime#2]
There is two project types
* Old csproj format
* New SDK-style csproj format

There is two way how to add webview2 files into project
* Via contentFiles folder (work only with new csproj)
* Via content folder and target file (work only with old csproj)

Combine of this two ways don't work. 
Try to find way how it can work in both project types, or it useless or not needed?

**Comment by superware** [comment]
Hi @ProKn1fe, thank you for a great package. Any idea how to operate with the old csproj? Thank you!

**Comment by ProKn1fe** [comment]
@superware if you have VS2017+ best scenario convert project to new format even if it net45 it will work. Otherwise only manually add WebView2 folder from nuget folder to project.

**Comment by superware** [comment]
@ProKn1fe thank you for your prompt reply. With a legacy csproj, do you happen to know what is the best way to manually copy  `soution_folder\packages\WebView2.Runtime.X64.114.0.1823.58\contentFiles\any\any\WebView2` to the output directory? Is there a $variable pointing to the package directory?

**Comment by ProKn1fe** [comment]
@superware i think you can automate copy this folder with post build script. With powershell something like:
```powershell
Find folder
$file = Get-ChildItem -Path $env:APPDATA\..\..\.nuget\packages -Filter "webview2.runtime.x64.*.nupkg" -Recurse
Calculate path
$input = $file.Directory.FullName + '\contentFiles\any\any\WebView2'
Copy
Copy-Item -Path $input -Destination "E:\" -Recurse
```

**Comment by superware** [comment]
Actually the following works, including copying to referencing projects:
```
<ItemGroup>
  <Content Include="$(SolutionDir)packages\WebView2.Runtime.X64.114.0.1823.58\contentFiles\any\any\**\*.*">
    <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <Visible>false</Visible>
  </Content>
</ItemGroup>
```
Only problem is the explicit `WebView2.Runtime.X64.114.0.1823.58` since `WebView2.Runtime.X64.*` changes the copied content to start at this folder and not `WebView2`. Any ideas?

Maybe just [Authoring packages for NuGet 2 and NuGet 3](https://learn.microsoft.com/en-us/nuget/archive/project-json-and-uwp#authoring-packages-for-nuget-2-and-nuget-3)?
