### ISSUE TITLE
How to get older version Webview2 runtime installer version 100.0.1185.29

### ISSUE THREAD

**Issue by Suresh-BabuLV** [ProKn1fe/WebView2.Runtime#6]
Hi Team,

We have project requirement to work on Webview2runtime version 100.0.1185.29.Need to download this version.
Please guide to download this version

Regards,
Suresh.

**Comment by ProKn1fe** [comment]
https://www.nuget.org/packages/WebView2.Runtime.X64/100.0.1185.29
https://www.nuget.org/packages/WebView2.Runtime.X86/100.0.1185.29

**Comment by westinyang** [comment]
I have archived WebView2 Fixed Version Runtime since the beginning of 2021, and currently I have collected versions 88 ~ 104. I created a repository and uploaded the archived files through Releases, hoping to help everyone!
https://github.com/westinyang/WebView2RuntimeArchive
