### ISSUE TITLE
How About 1 package contains all 3 runtimes?

### ISSUE THREAD

**Issue by DexterWoo** [ProKn1fe/WebView2.Runtime#7]
it's interesting, we are building a project that targets to generate both x64 binaries and Arm64 binaries.
is there a way for the project to conditionally include the runtime? 
like only if the platform is x64 will the x64 be copied, and only when the Platform is arm64 will the arm64 runtime be copied.

**Comment by ProKn1fe** [comment]
Nuget have 250mb package size limit, current 1 platform package size ~180mb. I think there is possible to try combine some files (like language packages), but I don't think it will be possible to get into this limit.

**Comment by ProKn1fe** [comment]
You can do something like that.
https://stackoverflow.com/questions/63540757/user-defined-condition-variable-for-package-referencing-in-c-sharp-net-core
In csproj:
`
	<ItemGroup Condition="$(Arch.Contains('X64'))">
	  <PackageReference Include="WebView2.Runtime.X64" Version="96.0.1054.29" />
	</ItemGroup>
	<ItemGroup Condition="$(Arch.Contains('X86'))">
	  <PackageReference Include="WebView2.Runtime.X86" Version="96.0.1054.29" />
	</ItemGroup>
`
And build with
`
dotnet build -p:Arch="X64"
`
This mean you will include different packages based on Arch parameter.
