### ISSUE TITLE
Has anyone managed to set it up with maui blazor?

### ISSUE THREAD

**Issue by iplusMario** [ProKn1fe/WebView2.Runtime#9]
I'm currently working on a maui blazor app that will run on a computer that doesn't have a browser installed.
So i tried to add your nuget package to my project and setting the environment variable WEBVIEW2_BROWSER_EXECUTABLE_FOLDER
to ```WebView2``` directory.

```
var directory = Directory.GetCurrentDirectory();
string fixedPath = Path.Combine(directory, "WebView2");
Environment.SetEnvironmentVariable("WEBVIEW2_BROWSER_EXECUTABLE_FOLDER", fixedPath);
```

But when I run the app I just get a blank page.

![image](https://user-images.githubusercontent.com/28944792/208016070-a8605c98-ea94-4303-8f70-83870bba81e8.png)

Any pointers on what I did wrong would be appreciated. 
Thanks in advance.

**Comment by ProKn1fe** [comment]
For some reason i think this env variable must exists before app starts.
`Environment.SetEnvironmentVariable("WEBVIEW2_BROWSER_EXECUTABLE_FOLDER", fixedPath);`

**Comment by iplusMario** [comment]
I tried adding it to the environment variables and still got the same result.

**Comment by ProKn1fe** [comment]
Feels like nothing to do here.
Here how it initialize webview2 in blazor maur:
https://github.com/dotnet/maui/blob/ff3e934de281ef241f84f85fa6c2825b390d732e/src/BlazorWebView/src/SharedSource/WebView2WebViewManager.cs

```C#
var args = new BlazorWebViewInitializingEventArgs();
#if WEBVIEW2_MAUI
_blazorWebViewHandler.VirtualView.BlazorWebViewInitializing(args);

try
{
_coreWebView2Environment = await CoreWebView2Environment.CreateWithOptionsAsync(
	browserExecutableFolder: args.BrowserExecutableFolder,
	userDataFolder: args.UserDataFolder,
	options: args.EnvironmentOptions)
	.AsTask()
	.ConfigureAwait(true);
}
catch (FileNotFoundException)
{
// This method needs to be invoked even if the WebView2 Runtime is not installed,
// since it is reponsible for creating the warning label and WebView2 Runtime
// download link.
await _webview.EnsureCoreWebView2Async();
return false;
}

await _webview.EnsureCoreWebView2Async();

var developerTools = _blazorWebViewHandler.DeveloperTools;
```

I don't see any options how we can access args here to put webview2 path directly.

You can try override webview2 path in registry:
https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/set-preview-channel.md#using-a-registry-override

I can't test this because windows didn't want me remove webview2 runtime for some reason xd.

**Comment by iplusMario** [comment]
I already looked at the source code from blazor and saw that there are no arguments to pass to initialize the WebView.
Then I checked maui github issues and noticed this comment which saying it can be done with environment variables.

https://github.com/dotnet/maui/pull/5086#issuecomment-1070779106

**Comment by ProKn1fe** [comment]
Interesting, why this commit only for winforms and wpf, i didn't see any reasons to not make same for maui.
